FROM ubuntu:20.04 
 
WORKDIR /app
 
RUN printf "\
deb http://10.67.69.28/artifactory/ubuntu-remote/ focal main restricted universe multiverse\
deb http://10.67.69.28/artifactory/ubuntu-remote/ focal-security main restricted universe multiverse\
deb http://10.67.69.28/artifactory/ubuntu-remote/ focal-updates main restricted universe multiverse\
deb http://10.67.69.28/artifactory/ubuntu-remote/ focal-backports main restricted universe multiverse\
deb https://mirrors.aliyun.com/kubernetes/apt kubernetes-xenial main\
deb https://mirrors.tuna.tsinghua.edu.cn/kubernetes/apt/ kubernetes-xenial main\
\n\n\
$(cat /etc/apt/sources.list)\
" > /etc/apt/sources.list

RUN apt-get update
RUN apt-get install -y vim-tiny net-tools iputils-ping curl bash-completion make
RUN chsh -s /bin/bash
RUN printf "\
$(cat ~/.bashrc)\
\n\
\n\
export PS1=\"🌻\[\033[01;32m\] \W\[\033[00m\] \"\
\n\
" > ~/.bashrc


RUN apt install -y apt-transport-https ca-certificates curl software-properties-common
# RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RUN curl -fsSL https://mirrors.ustc.edu.cn/docker-ce/linux/ubuntu/gpg | apt-key add -
#RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
RUN add-apt-repository "deb [arch=amd64] https://mirrors.ustc.edu.cn/docker-ce/linux/ubuntu $(lsb_release -cs) stable"
RUN apt update
RUN apt install -y docker-ce


CMD tail -f /dev/null
