spring:
  r2dbc:
    username: bodhi
    password: bodhicitta
    url: r2dbc:postgresql://localhost:54321/bodhitree

server:
  port: 8012

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
    file:     "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"

jwt:
  expiration:
    duration: 129600 # minutes
