BOX_NAME = "generic/ubuntu2010"
N = 3

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  (1..N).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.box = BOX_NAME
      node.vm.network "private_network", ip: "192.168.50.#{i}"
      node.vm.hostname = "node-#{i}"
    end
  end

end

