apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    # fill the right value below
    value: localhost:6379
  - name: redisPassword
    # fill the right value below
    value: ""
