debug: true

spring:
  application:
    name: BodhiTree.Auth
  boot:
    admin:
      client:
        url: http://127.0.0.1:9110 # admin server url

server:
  port: 8601

management:
  server:
    port: 7601
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

