debug: true
spring:
  application:
    name: BodhiTree.Gateway
  boot:
    admin:
      client:
        url: http://127.0.0.1:9110 # admin server url

server:
  port: 8600

management:
  server:
    port: 7600
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: TRACE

zuul.routes:
  auth:
    url: "http://localhost:8602"
  rest:
    url: "http://localhost:8602"

ribbon:
  eureka.enabled: false

