BOX_NAME = "generic/ubuntu2204"
N = 3

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  (1..N).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.box = BOX_NAME
      node.vm.network "private_network", ip: "192.168.50.1#{i}"
      node.vm.hostname = "node-#{i}"

      node.vm.provision "shell",
        # inline: "curl https://releases.rancher.com/install-docker/20.10.sh | sh"
        path: "install-docker-20.10.sh"

      # node.vm.provision "ansible" do |ansible|
      #   ansible.playbook = "node-playbook.yml"
      #   ansible.extra_vars = {
      #     node_ip: "192.168.50.1#{i}",
      #   }
      # end
    end
  end

end
