version: '3.0'

services:
  postgresdb:
    container_name: "bodhitree-postgresdb"
    image: postgres
    restart: unless-stopped
    volumes:
       - ./bodhitree-pgdata:/var/lib/postgresql/bodhitree-pgdata
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: bodhi
      POSTGRES_PASSWORD: bodhicitta
      POSTGRES_DB: bodhitree
      PGDATA: /var/lib/postgresql/bodhitree-pgdata
