version: '3'

services:
  single-node-cluster:
    container_name: rancher-kube-single-node-cluster
    image: rancher/rancher:latest
    restart: "unless-stopped"
    network_mode: host
    # ports:
    #   - 80:80
    #   - 443:443
    privileged: true
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '4g'
    memswap_limit: '4g'
    volumes:
      - ../..:/SunnyClouds
